import { IGRPMenuItemArgs } from '@igrp/framework-next-types';

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 1,
    name: 'Parametrizações',
    type: 'FOLDER',
    position: 1,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: null,
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 2,
    name: 'Base',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/options',
    parentId: 1,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 3,
    name: 'Licenciamento',
    type: 'MENU_PAGE',
    position: 2,
    icon: 'UserCog',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/parametrizacao',

    parentId: 1,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 4,
    name: 'Test Roles',
    type: 'EXTERNAL_PAGE',
    position: 2,
    icon: 'Users',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/roles',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  // {
  //   id: 9,
  //   name: 'NOSi',
  //   type: 'EXTERNAL_PAGE',
  //   position: 4,
  //   icon: 'Activity',
  //   status: 'ACTIVE',
  //   target: 'INTERNAL',
  //   url: 'https://nosi.cv',
  //   parentId: null,
  //   applicationId: 1,
  //   resourceId: null,
  //   createdBy: 'admin',
  //   createdDate: '2022-01-01T12:00:00.000Z',
  //   lastModifiedBy: 'admin',
  //   lastModifiedDate: '2022-01-01T12:00:00.000Z',
  // },
  {
    id: 5,
    name: 'Home',
    type: 'FOLDER',
    position: 3,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: null,
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 6,
    name: 'Settings',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/system-settings',
    parentId: 5,
    applicationId: 1,
    resourceId: null,
  },
];
